import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SessionProvider from '@/components/SessionProvider';
import { getServerSession } from 'next-auth';
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from '@mui/material';
import darkTheme from '@/theme/darkTheme';
import ColorModeProvider from '@/components/ColorModeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ColorModeProvider>
          <SessionProvider session={session}>
            <CssBaseline />
            {children}
          </SessionProvider>
        </ColorModeProvider>
      </body>
    </html>
  );
}
